import { ORDER_BY } from "@/lib/constants";

export const QUERY_USER_CHATS_LIMIT = 40;
export const QUERY_USER_CHATS_ORDER_BY = ORDER_BY.UPDATED_AT;
export const QUERY_USER_SHARED_CHATS_DESKTOP_LIMIT = 20;
export const QUERY_USER_SHARED_CHATS_MOBILE_LIMIT = 10;
export const QUERY_SEARCH_USER_CHATS_LIMIT = 25;
export const INITIAL_QUERY_SEARCH_USER_CHATS_LIMIT = 15;
