export const USER_ROLE_PLACEHOLDERS = [
    "Software Engineer",
    "Product Manager",
    "UX Designer",
    "Marketing Manager",
    "Sales Manager",
    "HR Manager",
    "Financial Analyst",
    "Project Manager",
    "Teacher",
    "Doctor",
    "Nurse",
    "Photographer",
    "Journalist",
    "Musician",
    "Chef",
    "Pilot",
    "Firefighter",
    "Student",
    "Athlete",
    "Level 10 Mage",
] as const;
